
#include <Core.hpp>
#include "Input/Input.h"

namespace ME::Input
{
#ifdef PLATFORM_WINDOWS
	Keycode InputController::ConvertPlatformKeycode(WORD keycode)
	{
		BEGIN_KEYCODE_CONVERTATION;

		// LETTERS (1 - 26)

		ADD_KEYCODE(0x41, ME_KEY_A);
		ADD_KEYCODE(0x42, ME_KEY_B);
		ADD_KEYCODE(0x43, ME_KEY_C);
		ADD_KEYCODE(0x44, ME_KEY_D);
		ADD_KEYCODE(0x45, ME_KEY_E);
		ADD_KEYCODE(0x46, ME_KEY_F);
		ADD_KEYCODE(0x47, ME_KEY_G);
		ADD_KEYCODE(0x48, ME_KEY_H);
		ADD_KEYCODE(0x49, ME_KEY_I);
		ADD_KEYCODE(0x4A, ME_KEY_J);
		ADD_KEYCODE(0x4B, ME_KEY_K);
		ADD_KEYCODE(0x4C, ME_KEY_L);
		ADD_KEYCODE(0x4D, ME_KEY_M);
		ADD_KEYCODE(0x4E, ME_KEY_N);
		ADD_KEYCODE(0x4F, ME_KEY_O);
		ADD_KEYCODE(0x50, ME_KEY_P);
		ADD_KEYCODE(0x51, ME_KEY_Q);
		ADD_KEYCODE(0x52, ME_KEY_R);
		ADD_KEYCODE(0x53, ME_KEY_S);
		ADD_KEYCODE(0x54, ME_KEY_T);
		ADD_KEYCODE(0x55, ME_KEY_U);
		ADD_KEYCODE(0x56, ME_KEY_V);
		ADD_KEYCODE(0x57, ME_KEY_W);
		ADD_KEYCODE(0x58, ME_KEY_X);
		ADD_KEYCODE(0x59, ME_KEY_Y);
		ADD_KEYCODE(0x5A, ME_KEY_Z);

		// Numbers (30 - 39)

		ADD_KEYCODE(0x30, ME_KEY_0);
		ADD_KEYCODE(0x31, ME_KEY_1);
		ADD_KEYCODE(0x32, ME_KEY_2);
		ADD_KEYCODE(0x33, ME_KEY_3);
		ADD_KEYCODE(0x34, ME_KEY_4);
		ADD_KEYCODE(0x35, ME_KEY_5);
		ADD_KEYCODE(0x36, ME_KEY_6);
		ADD_KEYCODE(0x37, ME_KEY_7);
		ADD_KEYCODE(0x38, ME_KEY_8);
		ADD_KEYCODE(0x39, ME_KEY_9);


		ADD_KEYCODE(VK_OEM_1, ME_KEY_SEMICOLON);
		ADD_KEYCODE(VK_OEM_2, ME_KEY_SLASH);
		ADD_KEYCODE(VK_OEM_3, ME_KEY_GRAVE);
		ADD_KEYCODE(VK_OEM_4, ME_KEY_LEFTBRACKET);
		ADD_KEYCODE(VK_OEM_5, ME_KEY_BACKSLASH);
		ADD_KEYCODE(VK_OEM_6, ME_KEY_RIGHTBRACKET);
		ADD_KEYCODE(VK_OEM_7, ME_KEY_APOSTROPHE);


		ADD_KEYCODE(VK_OEM_PLUS, ME_KEY_EQUAL);
		ADD_KEYCODE(VK_OEM_MINUS, ME_KEY_MINUS);
		ADD_KEYCODE(VK_OEM_COMMA, ME_KEY_COMMA);
		ADD_KEYCODE(VK_OEM_PERIOD, ME_KEY_PERIOD);
		ADD_KEYCODE(VK_LSHIFT, ME_KEY_LEFTSHIFT);
		ADD_KEYCODE(VK_RSHIFT, ME_KEY_RIGHTSHIFT);
		ADD_KEYCODE(VK_LMENU, ME_KEY_LEFTALT);
		ADD_KEYCODE(VK_RMENU, ME_KEY_RIGHTALT);
		ADD_KEYCODE(VK_LCONTROL, ME_KEY_LEFTCONTROL);
		ADD_KEYCODE(VK_RCONTROL, ME_KEY_RIGHTCONTROL);
		ADD_KEYCODE(VK_LWIN, ME_KEY_LEFTCOMMAND);
		ADD_KEYCODE(VK_RWIN, ME_KEY_RIGHTCOMMAND);
		ADD_KEYCODE(VK_CAPITAL, ME_KEY_CAPSLOCK);
		ADD_KEYCODE(VK_ESCAPE, ME_KEY_ESCAPE);
		ADD_KEYCODE(VK_SPACE, ME_KEY_SPACE);
		ADD_KEYCODE(VK_RETURN, ME_KEY_ENTER);
		ADD_KEYCODE(VK_TAB, ME_KEY_TAB);
		ADD_KEYCODE(VK_BACK, ME_KEY_BACKSPACE);
		ADD_KEYCODE(VK_UP, ME_KEY_UP);
		ADD_KEYCODE(VK_DOWN, ME_KEY_DOWN);
		ADD_KEYCODE(VK_LEFT, ME_KEY_LEFT);
		ADD_KEYCODE(VK_RIGHT, ME_KEY_RIGHT);
		ADD_KEYCODE(VK_DELETE, ME_KEY_DELETE);
		ADD_KEYCODE(VK_INSERT, ME_KEY_INSERT);
		ADD_KEYCODE(VK_END, ME_KEY_END);
		ADD_KEYCODE(VK_HOME, ME_KEY_HOME);
		ADD_KEYCODE(VK_SNAPSHOT, ME_KEY_PRINTSCREEN);
		ADD_KEYCODE(VK_NUMLOCK, ME_KEY_NUMLOCK);
		ADD_KEYCODE(VK_SCROLL, ME_KEY_SCROLLLOCK);
		ADD_KEYCODE(VK_F1, ME_KEY_F1);
		ADD_KEYCODE(VK_F2, ME_KEY_F2);
		ADD_KEYCODE(VK_F3, ME_KEY_F3);
		ADD_KEYCODE(VK_F4, ME_KEY_F4);
		ADD_KEYCODE(VK_F5, ME_KEY_F5);
		ADD_KEYCODE(VK_F6, ME_KEY_F6);
		ADD_KEYCODE(VK_F7, ME_KEY_F7);
		ADD_KEYCODE(VK_F8, ME_KEY_F8);
		ADD_KEYCODE(VK_F9, ME_KEY_F9);
		ADD_KEYCODE(VK_F10, ME_KEY_F10);
		ADD_KEYCODE(VK_F11, ME_KEY_F11);
		ADD_KEYCODE(VK_F12, ME_KEY_F12);
		ADD_KEYCODE(VK_PRIOR, ME_KEY_PAGEUP);
		ADD_KEYCODE(VK_NEXT, ME_KEY_PAGEDOWN);
		ADD_KEYCODE(VK_CLEAR, ME_KEY_CLEAR);

		ADD_KEYCODE(VK_NUMPAD0, ME_KEY_KP_0);
		ADD_KEYCODE(VK_NUMPAD1, ME_KEY_KP_1);
		ADD_KEYCODE(VK_NUMPAD2, ME_KEY_KP_2);
		ADD_KEYCODE(VK_NUMPAD3, ME_KEY_KP_3);
		ADD_KEYCODE(VK_NUMPAD4, ME_KEY_KP_4);
		ADD_KEYCODE(VK_NUMPAD5, ME_KEY_KP_5);
		ADD_KEYCODE(VK_NUMPAD6, ME_KEY_KP_6);
		ADD_KEYCODE(VK_NUMPAD7, ME_KEY_KP_7);
		ADD_KEYCODE(VK_NUMPAD8, ME_KEY_KP_8);
		ADD_KEYCODE(VK_NUMPAD9, ME_KEY_KP_9);
		ADD_KEYCODE(VK_ADD, ME_KEY_KP_PLUS);
		ADD_KEYCODE(VK_SUBTRACT, ME_KEY_KP_MINUS);
		ADD_KEYCODE(VK_MULTIPLY, ME_KEY_KP_MULTIPLY);
		ADD_KEYCODE(VK_DECIMAL, ME_KEY_KP_DOT);
		ADD_KEYCODE(VK_DIVIDE, ME_KEY_KP_DIVIDE);
		ADD_KEYCODE(VK_SEPARATOR, ME_KEY_KP_ENTER);

		END_KEYCODE_CONVERTATION;
	}

#endif

}