
#include "Core.h"
#include "Input/Input.h"

namespace Pawn::Input
{
#ifdef PLATFORM_WINDOWS
	Keycode InputController::ConvertPlatformKeycode(WORD keycode)
	{
		BEGIN_KEYCODE_CONVERTATION;

		// LETTERS (1 - 26)

		ADD_KEYCODE(0x41, PE_KEY_A);
		ADD_KEYCODE(0x42, PE_KEY_B);
		ADD_KEYCODE(0x43, PE_KEY_C);
		ADD_KEYCODE(0x44, PE_KEY_D);
		ADD_KEYCODE(0x45, PE_KEY_E);
		ADD_KEYCODE(0x46, PE_KEY_F);
		ADD_KEYCODE(0x47, PE_KEY_G);
		ADD_KEYCODE(0x48, PE_KEY_H);
		ADD_KEYCODE(0x49, PE_KEY_I);
		ADD_KEYCODE(0x4A, PE_KEY_J);
		ADD_KEYCODE(0x4B, PE_KEY_K);
		ADD_KEYCODE(0x4C, PE_KEY_L);
		ADD_KEYCODE(0x4D, PE_KEY_M);
		ADD_KEYCODE(0x4E, PE_KEY_N);
		ADD_KEYCODE(0x4F, PE_KEY_O);
		ADD_KEYCODE(0x50, PE_KEY_P);
		ADD_KEYCODE(0x51, PE_KEY_Q);
		ADD_KEYCODE(0x52, PE_KEY_R);
		ADD_KEYCODE(0x53, PE_KEY_S);
		ADD_KEYCODE(0x54, PE_KEY_T);
		ADD_KEYCODE(0x55, PE_KEY_U);
		ADD_KEYCODE(0x56, PE_KEY_V);
		ADD_KEYCODE(0x57, PE_KEY_W);
		ADD_KEYCODE(0x58, PE_KEY_X);
		ADD_KEYCODE(0x59, PE_KEY_Y);
		ADD_KEYCODE(0x5A, PE_KEY_Z);

		// Numbers (30 - 39)

		ADD_KEYCODE(0x30, PE_KEY_0);
		ADD_KEYCODE(0x31, PE_KEY_1);
		ADD_KEYCODE(0x32, PE_KEY_2);
		ADD_KEYCODE(0x33, PE_KEY_3);
		ADD_KEYCODE(0x34, PE_KEY_4);
		ADD_KEYCODE(0x35, PE_KEY_5);
		ADD_KEYCODE(0x36, PE_KEY_6);
		ADD_KEYCODE(0x37, PE_KEY_7);
		ADD_KEYCODE(0x38, PE_KEY_8);
		ADD_KEYCODE(0x39, PE_KEY_9);


		ADD_KEYCODE(VK_OEM_1, PE_KEY_SEMICOLON);
		ADD_KEYCODE(VK_OEM_2, PE_KEY_SLASH);
		ADD_KEYCODE(VK_OEM_3, PE_KEY_GRAVE);
		ADD_KEYCODE(VK_OEM_4, PE_KEY_LEFTBRACKET);
		ADD_KEYCODE(VK_OEM_5, PE_KEY_BACKSLASH);
		ADD_KEYCODE(VK_OEM_6, PE_KEY_RIGHTBRACKET);
		ADD_KEYCODE(VK_OEM_7, PE_KEY_APOSTROPHE);


		ADD_KEYCODE(VK_OEM_PLUS, PE_KEY_EQUAL);
		ADD_KEYCODE(VK_OEM_MINUS, PE_KEY_MINUS);
		ADD_KEYCODE(VK_OEM_COMMA, PE_KEY_COMMA);
		ADD_KEYCODE(VK_OEM_PERIOD, PE_KEY_PERIOD);
		ADD_KEYCODE(VK_LSHIFT, PE_KEY_LEFTSHIFT);
		ADD_KEYCODE(VK_RSHIFT, PE_KEY_RIGHTSHIFT);
		ADD_KEYCODE(VK_LMENU, PE_KEY_LEFTALT);
		ADD_KEYCODE(VK_RMENU, PE_KEY_RIGHTALT);
		ADD_KEYCODE(VK_LCONTROL, PE_KEY_LEFTCONTROL);
		ADD_KEYCODE(VK_RCONTROL, PE_KEY_RIGHTCONTROL);
		ADD_KEYCODE(VK_LWIN, PE_KEY_LEFTCOMMAND);
		ADD_KEYCODE(VK_RWIN, PE_KEY_RIGHTCOMMAND);
		ADD_KEYCODE(VK_CAPITAL, PE_KEY_CAPSLOCK);
		ADD_KEYCODE(VK_ESCAPE, PE_KEY_ESCAPE);
		ADD_KEYCODE(VK_SPACE, PE_KEY_SPACE);
		ADD_KEYCODE(VK_RETURN, PE_KEY_ENTER);
		ADD_KEYCODE(VK_TAB, PE_KEY_TAB);
		ADD_KEYCODE(VK_BACK, PE_KEY_BACKSPACE);
		ADD_KEYCODE(VK_UP, PE_KEY_UP);
		ADD_KEYCODE(VK_DOWN, PE_KEY_DOWN);
		ADD_KEYCODE(VK_LEFT, PE_KEY_LEFT);
		ADD_KEYCODE(VK_RIGHT, PE_KEY_RIGHT);
		ADD_KEYCODE(VK_DELETE, PE_KEY_DELETE);
		ADD_KEYCODE(VK_INSERT, PE_KEY_INSERT);
		ADD_KEYCODE(VK_END, PE_KEY_END);
		ADD_KEYCODE(VK_HOME, PE_KEY_HOME);
		ADD_KEYCODE(VK_SNAPSHOT, PE_KEY_PRINTSCREEN);
		ADD_KEYCODE(VK_NUMLOCK, PE_KEY_NUMLOCK);
		ADD_KEYCODE(VK_SCROLL, PE_KEY_SCROLLLOCK);
		ADD_KEYCODE(VK_F1, PE_KEY_F1);
		ADD_KEYCODE(VK_F2, PE_KEY_F2);
		ADD_KEYCODE(VK_F3, PE_KEY_F3);
		ADD_KEYCODE(VK_F4, PE_KEY_F4);
		ADD_KEYCODE(VK_F5, PE_KEY_F5);
		ADD_KEYCODE(VK_F6, PE_KEY_F6);
		ADD_KEYCODE(VK_F7, PE_KEY_F7);
		ADD_KEYCODE(VK_F8, PE_KEY_F8);
		ADD_KEYCODE(VK_F9, PE_KEY_F9);
		ADD_KEYCODE(VK_F10, PE_KEY_F10);
		ADD_KEYCODE(VK_F11, PE_KEY_F11);
		ADD_KEYCODE(VK_F12, PE_KEY_F12);
		ADD_KEYCODE(VK_PRIOR, PE_KEY_PAGEUP);
		ADD_KEYCODE(VK_NEXT, PE_KEY_PAGEDOWN);
		ADD_KEYCODE(VK_CLEAR, PE_KEY_CLEAR);

		ADD_KEYCODE(VK_NUMPAD0, PE_KEY_KP_0);
		ADD_KEYCODE(VK_NUMPAD1, PE_KEY_KP_1);
		ADD_KEYCODE(VK_NUMPAD2, PE_KEY_KP_2);
		ADD_KEYCODE(VK_NUMPAD3, PE_KEY_KP_3);
		ADD_KEYCODE(VK_NUMPAD4, PE_KEY_KP_4);
		ADD_KEYCODE(VK_NUMPAD5, PE_KEY_KP_5);
		ADD_KEYCODE(VK_NUMPAD6, PE_KEY_KP_6);
		ADD_KEYCODE(VK_NUMPAD7, PE_KEY_KP_7);
		ADD_KEYCODE(VK_NUMPAD8, PE_KEY_KP_8);
		ADD_KEYCODE(VK_NUMPAD9, PE_KEY_KP_9);
		ADD_KEYCODE(VK_ADD, PE_KEY_KP_PLUS);
		ADD_KEYCODE(VK_SUBTRACT, PE_KEY_KP_MINUS);
		ADD_KEYCODE(VK_MULTIPLY, PE_KEY_KP_MULTIPLY);
		ADD_KEYCODE(VK_DECIMAL, PE_KEY_KP_DOT);
		ADD_KEYCODE(VK_DIVIDE, PE_KEY_KP_DIVIDE);
		ADD_KEYCODE(VK_SEPARATOR, PE_KEY_KP_ENTER);

		END_KEYCODE_CONVERTATION;
	}

#endif

}