#pragma once

#define ENGINE_NAME "Moon Engine"
#define ENGINE_NAMEW L"Moon Engine"

// v1.v2.v3
#define ENGINE_VER_MAJOR 1
#define ENGINE_VER_MINOR 0
#define ENGINE_VER_PATCH 0

#define ENGINE_VERSION ENGINE_VER_MAJOR, ENGINE_VER_MINOR, ENGINE_VER_PATCH

#define ME_SHADER_DEBUG